%%
%% Autogenerated by Thrift Compiler (0.19.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(iotdb_common_types).

-include("iotdb_common_types.hrl").

-export([struct_info/1, struct_info_ext/1, enum_info/1, enum_names/0, struct_names/0, exception_names/0]).

struct_info('tEndPoint') ->
  {struct, [{1, string},
          {2, i32}]}
;

struct_info('tSStatus') ->
  {struct, [{1, i32},
          {2, string},
          {3, {list, {struct, {'iotdb_common_types', 'tSStatus'}}}},
          {4, {struct, {'iotdb_common_types', 'tEndPoint'}}},
          {5, bool}]}
;

struct_info('tConsensusGroupId') ->
  {struct, [{1, i32},
          {2, i32}]}
;

struct_info('tSeriesPartitionSlot') ->
  {struct, [{1, i32}]}
;

struct_info('tTimePartitionSlot') ->
  {struct, [{1, i64}]}
;

struct_info('tRegionReplicaSet') ->
  {struct, [{1, {struct, {'iotdb_common_types', 'tConsensusGroupId'}}},
          {2, {list, {struct, {'iotdb_common_types', 'tDataNodeLocation'}}}}]}
;

struct_info('tNodeResource') ->
  {struct, [{1, i32},
          {2, i64}]}
;

struct_info('tConfigNodeLocation') ->
  {struct, [{1, i32},
          {2, {struct, {'iotdb_common_types', 'tEndPoint'}}},
          {3, {struct, {'iotdb_common_types', 'tEndPoint'}}}]}
;

struct_info('tDataNodeLocation') ->
  {struct, [{1, i32},
          {2, {struct, {'iotdb_common_types', 'tEndPoint'}}},
          {3, {struct, {'iotdb_common_types', 'tEndPoint'}}},
          {4, {struct, {'iotdb_common_types', 'tEndPoint'}}},
          {5, {struct, {'iotdb_common_types', 'tEndPoint'}}},
          {6, {struct, {'iotdb_common_types', 'tEndPoint'}}}]}
;

struct_info('tAINodeLocation') ->
  {struct, [{1, i32},
          {2, {struct, {'iotdb_common_types', 'tEndPoint'}}}]}
;

struct_info('tDataNodeConfiguration') ->
  {struct, [{1, {struct, {'iotdb_common_types', 'tDataNodeLocation'}}},
          {2, {struct, {'iotdb_common_types', 'tNodeResource'}}}]}
;

struct_info('tAINodeConfiguration') ->
  {struct, [{1, {struct, {'iotdb_common_types', 'tAINodeLocation'}}},
          {2, {struct, {'iotdb_common_types', 'tNodeResource'}}}]}
;

struct_info('tFlushReq') ->
  {struct, [{1, string},
          {2, {list, string}},
          {3, {list, string}}]}
;

struct_info('tSettleReq') ->
  {struct, [{1, {list, string}}]}
;

struct_info('tSchemaNode') ->
  {struct, [{1, string},
          {2, byte}]}
;

struct_info('tSetConfigurationReq') ->
  {struct, [{1, {map, string, string}},
          {2, i32}]}
;

struct_info('tSetTTLReq') ->
  {struct, [{1, {list, string}},
          {2, i64},
          {3, bool}]}
;

struct_info('tShowTTLReq') ->
  {struct, [{1, {list, string}}]}
;

struct_info('tFile') ->
  {struct, [{1, string},
          {2, string}]}
;

struct_info('tFilesResp') ->
  {struct, [{1, {struct, {'iotdb_common_types', 'tSStatus'}}},
          {2, {list, {struct, {'iotdb_common_types', 'tFile'}}}}]}
;

struct_info('tSpaceQuota') ->
  {struct, [{1, i64},
          {2, i64},
          {3, i64}]}
;

struct_info('tTimedQuota') ->
  {struct, [{1, i64},
          {2, i64}]}
;

struct_info('tThrottleQuota') ->
  {struct, [{1, {map, i32, {struct, {'iotdb_common_types', 'tTimedQuota'}}}},
          {2, i64},
          {3, i32}]}
;

struct_info('tSetSpaceQuotaReq') ->
  {struct, [{1, {list, string}},
          {2, {struct, {'iotdb_common_types', 'tSpaceQuota'}}}]}
;

struct_info('tSetThrottleQuotaReq') ->
  {struct, [{1, string},
          {2, {struct, {'iotdb_common_types', 'tThrottleQuota'}}}]}
;

struct_info('tPipeHeartbeatResp') ->
  {struct, [{1, {list, string}},
          {2, {list, bool}},
          {3, {list, i64}},
          {4, {list, double}}]}
;

struct_info('tLicense') ->
  {struct, [{1, i64},
          {2, i64},
          {4, i16},
          {5, i32},
          {6, i64},
          {7, i64},
          {8, i64},
          {9, i16}]}
;

struct_info('tLoadSample') ->
  {struct, [{1, double},
          {2, double},
          {3, double},
          {4, double}]}
;

struct_info('tServiceProvider') ->
  {struct, [{1, {struct, {'iotdb_common_types', 'tEndPoint'}}},
          {2, i32},
          {3, i32}]}
;

struct_info('tSender') ->
  {struct, [{1, {struct, {'iotdb_common_types', 'tDataNodeLocation'}}},
          {2, {struct, {'iotdb_common_types', 'tConfigNodeLocation'}}}]}
;

struct_info('tTestConnectionResult') ->
  {struct, [{1, {struct, {'iotdb_common_types', 'tServiceProvider'}}},
          {2, {struct, {'iotdb_common_types', 'tSender'}}},
          {3, bool},
          {4, string}]}
;

struct_info('tTestConnectionResp') ->
  {struct, [{1, {struct, {'iotdb_common_types', 'tSStatus'}}},
          {2, {list, {struct, {'iotdb_common_types', 'tTestConnectionResult'}}}}]}
;

struct_info('tNodeLocations') ->
  {struct, [{1, {list, {struct, {'iotdb_common_types', 'tConfigNodeLocation'}}}},
          {2, {list, {struct, {'iotdb_common_types', 'tDataNodeLocation'}}}}]}
;

struct_info('tShowConfigurationTemplateResp') ->
  {struct, [{1, {struct, {'iotdb_common_types', 'tSStatus'}}},
          {2, string}]}
;

struct_info('tShowConfigurationResp') ->
  {struct, [{1, {struct, {'iotdb_common_types', 'tSStatus'}}},
          {2, string}]}
;

struct_info('tShowAppliedConfigurationsResp') ->
  {struct, [{1, {struct, {'iotdb_common_types', 'tSStatus'}}},
          {2, {map, string, string}}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('tEndPoint') ->
  {struct, [{1, required, string, 'ip', undefined},
          {2, required, i32, 'port', undefined}]}
;

struct_info_ext('tSStatus') ->
  {struct, [{1, required, i32, 'code', undefined},
          {2, optional, string, 'message', undefined},
          {3, optional, {list, {struct, {'iotdb_common_types', 'tSStatus'}}}, 'subStatus', []},
          {4, optional, {struct, {'iotdb_common_types', 'tEndPoint'}}, 'redirectNode', #'tEndPoint'{}},
          {5, optional, bool, 'needRetry', undefined}]}
;

struct_info_ext('tConsensusGroupId') ->
  {struct, [{1, required, i32, 'type', undefined},
          {2, required, i32, 'id', undefined}]}
;

struct_info_ext('tSeriesPartitionSlot') ->
  {struct, [{1, required, i32, 'slotId', undefined}]}
;

struct_info_ext('tTimePartitionSlot') ->
  {struct, [{1, required, i64, 'startTime', undefined}]}
;

struct_info_ext('tRegionReplicaSet') ->
  {struct, [{1, required, {struct, {'iotdb_common_types', 'tConsensusGroupId'}}, 'regionId', #'tConsensusGroupId'{}},
          {2, required, {list, {struct, {'iotdb_common_types', 'tDataNodeLocation'}}}, 'dataNodeLocations', []}]}
;

struct_info_ext('tNodeResource') ->
  {struct, [{1, required, i32, 'cpuCoreNum', undefined},
          {2, required, i64, 'maxMemory', undefined}]}
;

struct_info_ext('tConfigNodeLocation') ->
  {struct, [{1, required, i32, 'configNodeId', undefined},
          {2, required, {struct, {'iotdb_common_types', 'tEndPoint'}}, 'internalEndPoint', #'tEndPoint'{}},
          {3, required, {struct, {'iotdb_common_types', 'tEndPoint'}}, 'consensusEndPoint', #'tEndPoint'{}}]}
;

struct_info_ext('tDataNodeLocation') ->
  {struct, [{1, required, i32, 'dataNodeId', undefined},
          {2, required, {struct, {'iotdb_common_types', 'tEndPoint'}}, 'clientRpcEndPoint', #'tEndPoint'{}},
          {3, required, {struct, {'iotdb_common_types', 'tEndPoint'}}, 'internalEndPoint', #'tEndPoint'{}},
          {4, required, {struct, {'iotdb_common_types', 'tEndPoint'}}, 'mPPDataExchangeEndPoint', #'tEndPoint'{}},
          {5, required, {struct, {'iotdb_common_types', 'tEndPoint'}}, 'dataRegionConsensusEndPoint', #'tEndPoint'{}},
          {6, required, {struct, {'iotdb_common_types', 'tEndPoint'}}, 'schemaRegionConsensusEndPoint', #'tEndPoint'{}}]}
;

struct_info_ext('tAINodeLocation') ->
  {struct, [{1, required, i32, 'aiNodeId', undefined},
          {2, required, {struct, {'iotdb_common_types', 'tEndPoint'}}, 'internalEndPoint', #'tEndPoint'{}}]}
;

struct_info_ext('tDataNodeConfiguration') ->
  {struct, [{1, required, {struct, {'iotdb_common_types', 'tDataNodeLocation'}}, 'location', #'tDataNodeLocation'{}},
          {2, required, {struct, {'iotdb_common_types', 'tNodeResource'}}, 'resource', #'tNodeResource'{}}]}
;

struct_info_ext('tAINodeConfiguration') ->
  {struct, [{1, required, {struct, {'iotdb_common_types', 'tAINodeLocation'}}, 'location', #'tAINodeLocation'{}},
          {2, required, {struct, {'iotdb_common_types', 'tNodeResource'}}, 'resource', #'tNodeResource'{}}]}
;

struct_info_ext('tFlushReq') ->
  {struct, [{1, optional, string, 'isSeq', undefined},
          {2, optional, {list, string}, 'storageGroups', []},
          {3, optional, {list, string}, 'regionIds', []}]}
;

struct_info_ext('tSettleReq') ->
  {struct, [{1, required, {list, string}, 'paths', []}]}
;

struct_info_ext('tSchemaNode') ->
  {struct, [{1, required, string, 'nodeName', undefined},
          {2, required, byte, 'nodeType', undefined}]}
;

struct_info_ext('tSetConfigurationReq') ->
  {struct, [{1, required, {map, string, string}, 'configs', #{}},
          {2, required, i32, 'nodeId', undefined}]}
;

struct_info_ext('tSetTTLReq') ->
  {struct, [{1, required, {list, string}, 'pathPattern', []},
          {2, required, i64, 'tTL', undefined},
          {3, required, bool, 'isDataBase', undefined}]}
;

struct_info_ext('tShowTTLReq') ->
  {struct, [{1, required, {list, string}, 'pathPattern', []}]}
;

struct_info_ext('tFile') ->
  {struct, [{1, required, string, 'fileName', undefined},
          {2, required, string, 'file', undefined}]}
;

struct_info_ext('tFilesResp') ->
  {struct, [{1, required, {struct, {'iotdb_common_types', 'tSStatus'}}, 'status', #'tSStatus'{}},
          {2, required, {list, {struct, {'iotdb_common_types', 'tFile'}}}, 'files', []}]}
;

struct_info_ext('tSpaceQuota') ->
  {struct, [{1, optional, i64, 'diskSize', undefined},
          {2, optional, i64, 'deviceNum', undefined},
          {3, optional, i64, 'timeserieNum', undefined}]}
;

struct_info_ext('tTimedQuota') ->
  {struct, [{1, required, i64, 'timeUnit', undefined},
          {2, required, i64, 'softLimit', undefined}]}
;

struct_info_ext('tThrottleQuota') ->
  {struct, [{1, optional, {map, i32, {struct, {'iotdb_common_types', 'tTimedQuota'}}}, 'throttleLimit', #{}},
          {2, optional, i64, 'memLimit', undefined},
          {3, optional, i32, 'cpuLimit', undefined}]}
;

struct_info_ext('tSetSpaceQuotaReq') ->
  {struct, [{1, required, {list, string}, 'database', []},
          {2, required, {struct, {'iotdb_common_types', 'tSpaceQuota'}}, 'spaceLimit', #'tSpaceQuota'{}}]}
;

struct_info_ext('tSetThrottleQuotaReq') ->
  {struct, [{1, required, string, 'userName', undefined},
          {2, required, {struct, {'iotdb_common_types', 'tThrottleQuota'}}, 'throttleQuota', #'tThrottleQuota'{}}]}
;

struct_info_ext('tPipeHeartbeatResp') ->
  {struct, [{1, required, {list, string}, 'pipeMetaList', []},
          {2, optional, {list, bool}, 'pipeCompletedList', []},
          {3, optional, {list, i64}, 'pipeRemainingEventCountList', []},
          {4, optional, {list, double}, 'pipeRemainingTimeList', []}]}
;

struct_info_ext('tLicense') ->
  {struct, [{1, required, i64, 'licenseIssueTimestamp', undefined},
          {2, required, i64, 'expireTimestamp', undefined},
          {4, required, i16, 'dataNodeNumLimit', undefined},
          {5, required, i32, 'cpuCoreNumLimit', undefined},
          {6, required, i64, 'deviceNumLimit', undefined},
          {7, required, i64, 'sensorNumLimit', undefined},
          {8, required, i64, 'disconnectionFromActiveNodeTimeLimit', undefined},
          {9, required, i16, 'mlNodeNumLimit', undefined}]}
;

struct_info_ext('tLoadSample') ->
  {struct, [{1, required, double, 'cpuUsageRate', undefined},
          {2, required, double, 'memoryUsageRate', undefined},
          {3, required, double, 'diskUsageRate', undefined},
          {4, required, double, 'freeDiskSpace', undefined}]}
;

struct_info_ext('tServiceProvider') ->
  {struct, [{1, required, {struct, {'iotdb_common_types', 'tEndPoint'}}, 'endPoint', #'tEndPoint'{}},
          {2, required, i32, 'serviceType', undefined},
          {3, required, i32, 'nodeId', undefined}]}
;

struct_info_ext('tSender') ->
  {struct, [{1, optional, {struct, {'iotdb_common_types', 'tDataNodeLocation'}}, 'dataNodeLocation', #'tDataNodeLocation'{}},
          {2, optional, {struct, {'iotdb_common_types', 'tConfigNodeLocation'}}, 'configNodeLocation', #'tConfigNodeLocation'{}}]}
;

struct_info_ext('tTestConnectionResult') ->
  {struct, [{1, required, {struct, {'iotdb_common_types', 'tServiceProvider'}}, 'serviceProvider', #'tServiceProvider'{}},
          {2, required, {struct, {'iotdb_common_types', 'tSender'}}, 'sender', #'tSender'{}},
          {3, required, bool, 'success', undefined},
          {4, optional, string, 'reason', undefined}]}
;

struct_info_ext('tTestConnectionResp') ->
  {struct, [{1, required, {struct, {'iotdb_common_types', 'tSStatus'}}, 'status', #'tSStatus'{}},
          {2, required, {list, {struct, {'iotdb_common_types', 'tTestConnectionResult'}}}, 'resultList', []}]}
;

struct_info_ext('tNodeLocations') ->
  {struct, [{1, optional, {list, {struct, {'iotdb_common_types', 'tConfigNodeLocation'}}}, 'configNodeLocations', []},
          {2, optional, {list, {struct, {'iotdb_common_types', 'tDataNodeLocation'}}}, 'dataNodeLocations', []}]}
;

struct_info_ext('tShowConfigurationTemplateResp') ->
  {struct, [{1, required, {struct, {'iotdb_common_types', 'tSStatus'}}, 'status', #'tSStatus'{}},
          {2, required, string, 'content', undefined}]}
;

struct_info_ext('tShowConfigurationResp') ->
  {struct, [{1, required, {struct, {'iotdb_common_types', 'tSStatus'}}, 'status', #'tSStatus'{}},
          {2, required, string, 'content', undefined}]}
;

struct_info_ext('tShowAppliedConfigurationsResp') ->
  {struct, [{1, required, {struct, {'iotdb_common_types', 'tSStatus'}}, 'status', #'tSStatus'{}},
          {2, optional, {map, string, string}, 'data', #{}}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

struct_names() ->
  ['tEndPoint', 'tSStatus', 'tConsensusGroupId', 'tSeriesPartitionSlot', 'tTimePartitionSlot', 'tRegionReplicaSet', 'tNodeResource', 'tConfigNodeLocation', 'tDataNodeLocation', 'tAINodeLocation', 'tDataNodeConfiguration', 'tAINodeConfiguration', 'tFlushReq', 'tSettleReq', 'tSchemaNode', 'tSetConfigurationReq', 'tSetTTLReq', 'tShowTTLReq', 'tFile', 'tFilesResp', 'tSpaceQuota', 'tTimedQuota', 'tThrottleQuota', 'tSetSpaceQuotaReq', 'tSetThrottleQuotaReq', 'tPipeHeartbeatResp', 'tLicense', 'tLoadSample', 'tServiceProvider', 'tSender', 'tTestConnectionResult', 'tTestConnectionResp', 'tNodeLocations', 'tShowConfigurationTemplateResp', 'tShowConfigurationResp', 'tShowAppliedConfigurationsResp'].

enum_info('tConsensusGroupType') ->
  [
    {'configRegion', 0},
    {'dataRegion', 1},
    {'schemaRegion', 2}
  ];

enum_info('tRegionMigrateFailedType') ->
  [
    {'addPeerFailed', 0},
    {'removePeerFailed', 1},
    {'removeConsensusGroupFailed', 2},
    {'deleteRegionFailed', 3},
    {'createRegionFailed', 4},
    {'disconnect', 5}
  ];

enum_info('tRegionMaintainTaskStatus') ->
  [
    {'tASK_NOT_EXIST', 0},
    {'pROCESSING', 1},
    {'sUCCESS', 2},
    {'fAIL', 3}
  ];

enum_info('throttleType') ->
  [
    {'rEQUEST_NUMBER', 0},
    {'rEQUEST_SIZE', 1},
    {'wRITE_NUMBER', 2},
    {'wRITE_SIZE', 3},
    {'rEAD_NUMBER', 4},
    {'rEAD_SIZE', 5}
  ];

enum_info('tServiceType') ->
  [
    {'configNodeInternalService', 0},
    {'dataNodeInternalService', 1},
    {'dataNodeMPPService', 2},
    {'dataNodeExternalService', 3}
  ];

enum_info('tAggregationType') ->
  [
    {'cOUNT', 0},
    {'aVG', 1},
    {'sUM', 2},
    {'fIRST_VALUE', 3},
    {'lAST_VALUE', 4},
    {'mAX_TIME', 5},
    {'mIN_TIME', 6},
    {'mAX_VALUE', 7},
    {'mIN_VALUE', 8},
    {'eXTREME', 9},
    {'cOUNT_IF', 10},
    {'tIME_DURATION', 11},
    {'mODE', 12},
    {'cOUNT_TIME', 13},
    {'sTDDEV', 14},
    {'sTDDEV_POP', 15},
    {'sTDDEV_SAMP', 16},
    {'vARIANCE', 17},
    {'vAR_POP', 18},
    {'vAR_SAMP', 19},
    {'mAX_BY', 20},
    {'mIN_BY', 21},
    {'uDAF', 22},
    {'fIRST', 23},
    {'lAST', 24},
    {'fIRST_BY', 25},
    {'lAST_BY', 26},
    {'mIN', 27},
    {'mAX', 28},
    {'cOUNT_ALL', 29},
    {'aPPROX_COUNT_DISTINCT', 30},
    {'aPPROX_MOST_FREQUENT', 31},
    {'aPPROX_PERCENTILE', 32}
  ];

enum_info('trainingState') ->
  [
    {'pENDING', 0},
    {'rUNNING', 1},
    {'fINISHED', 2},
    {'fAILED', 3},
    {'dROPPING', 4}
  ];

enum_info('model') ->
  [
    {'tREE', 0},
    {'tABLE', 1}
  ];

enum_info('functionType') ->
  [
    {'nONE', 0},
    {'sCALAR', 1},
    {'aGGREGATE', 2},
    {'tABLE', 3}
  ];

enum_info(_) -> erlang:error(function_clause).

enum_names() ->
  ['tConsensusGroupType', 'tRegionMigrateFailedType', 'tRegionMaintainTaskStatus', 'throttleType', 'tServiceType', 'tAggregationType', 'trainingState', 'model', 'functionType'].

exception_names() ->
  [].

