%%
%% Autogenerated by Thrift Compiler (0.19.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-ifndef(_iotdb_IClientRPCService_included).
-define(_iotdb_IClientRPCService_included, yeah).
-include("iotdb_client_types.hrl").

-endif.
